sudo: false
language: python
python: 2.7
services:
  - rabbitmq
  - mongodb
  - elasticsearch
env:
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=lint
install:
  - pip install tox coveralls
script:
  - tox -e $TOX_ENV
after_success: coveralls

deploy:
  provider: pypi
  user: tim.messier
  password:
    secure: OnU4/kHwHVKKOQv8gBtrpkbqrjF44ndvH37HmrtFFYnZDE3f4NB9CetwLykfDuDUQpACFvqTJtE8Y37RwTRpkl/N+GiTN8fSe8ca5uTMwnZiTPCqC9B8I/VGWByKcpszIhVtMjxlJh3avWEBRRlG4RuvqfwJXxBV+jOYBFiwBIQ=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    branch: master
