sudo: false
language: python
python: 2.7
services:
  - rabbitmq
  - mongodb
  - elasticsearch
env:
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=lint
before_install:
  - wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
  - gunzip GeoLiteCity.dat.gz
install:
  - pip install tox coveralls
script:
  - tox -e $TOX_ENV
after_success: coveralls

deploy:
  provider: pypi
  user: tim.messier
  password:
    secure: OnU4/kHwHVKKOQv8gBtrpkbqrjF44ndvH37HmrtFFYnZDE3f4NB9CetwLykfDuDUQpACFvqTJtE8Y37RwTRpkl/N+GiTN8fSe8ca5uTMwnZiTPCqC9B8I/VGWByKcpszIhVtMjxlJh3avWEBRRlG4RuvqfwJXxBV+jOYBFiwBIQ=
  distributions: "sdist bdist_wheel"
  on:
    condition: "$TOX_ENV = py27"
    tags: true
    branch: master
