#!/usr/bin/env python
# vim: set et ts=4 sw=4 fileencoding=utf-8:
'''
Script to run yalp
'''
from yalp import scripts


if __name__ == '__main__':
    scripts.ParsersEntryPoint(description='YALP - Parsers').execute()
